engines:
  structure:
    enabled: true
    channel: java
  duplication:
    enabled: true
    channel: java
ratings:
  paths:
    - "**.java"
exclude_paths:
  - "**.py*"
  - "**.js"
  - "**.jsx"
  - "**.rb"
